version: "3.8"

services:
  react-app:
    image: node:16-alpine # Use an appropriate Node.js image
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/graphql
      - REACT_APP_IMAGE_SERVER_URL=http://localhost:8000
    volumes:
      - ./beaconnect-react-app:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    restart: always
    depends_on:
      - graphql-gateway
      - local-storage-handler

  graphql-gateway:
    image: node:16-alpine
    ports:
      - "4000:4000"
    environment:
      - DB_URL=neo4j://beaconnet-neo4j:7687
      - DB_USER=neo4j
      - DB_PASSWORD=HduRGaPgz92Dl1fpjZ61ovqLKVGq5jEr-MCjbw2Ee4U
      - SALT_ROUND=1
      - SECRET=CSCI3100
    volumes:
      - ./graphql-gateway:/app
      - /app/node_modules
    working_dir: /app/js-graphql
    networks:
      - beaconnet
    command: yarn dev # Assuming `yarn start` is the correct command to run your server
    restart: always
    depends_on:
      - beaconnet-neo4j

  beaconnet-neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/HduRGaPgz92Dl1fpjZ61ovqLKVGq5jEr-MCjbw2Ee4U
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_max__size=2G # Corrected variable name
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: always
    networks:
      - beaconnet

  local-storage-handler:
    image: python:3.9
    command: sh -c "pip install -r requirement.txt && python main.py"
    ports:
      - "8000:8000"
    environment:
      - LOCAL_STORAGE_DIR=/dev/null # Use /dev/null to discard files
    volumes:
      - ./local-image-server:/app
    restart: always
    working_dir: /app/py-image-server

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  beaconnet: # Define the network referenced by the neo4j service
    driver: bridge
