version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "beaconnect-image"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rgi5jjohmf50"
s3_prefix = "beaconnect-image"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
